### ISSUE TITLE
Property Strings

### ISSUE THREAD

**Issue by vlow** [lokaler-kaufen/lokaler-kaufen-app#176]
Derzeit sind die meisten Texte hardcoded. Das war für den initialen Wurf gut genug, jetzt sollten wir beginnen auf Property Strings umzubauen und konsequent diese zu verwenden, da der Aufwand sonst später zu hoch wird.

**Comment by phxql** [comment]
Backend hat die Subjects der Emails hardcoded im `EmailServiceImpl`, die Email-Bodies sind als Textdateien im `src/main/resources`.

**Comment by zalintyre** [comment]
Wir haben Texte im Frontend und im Backend. Mein Vorschlag deswegen: Das Backend hat die Hoheit über die Texte und liefert diese (als JSON) an das Frontend aus. Dort verarbeiten wir das mit [ngx-translate](https://github.com/ngx-translate/core). 

@phxql @defaude ok so?

**Comment by phxql** [comment]
Hm, seh ich nicht so.

**Comment by zalintyre** [comment]
Die Idee war, die Texte zu zentralisieren. Aber ich kann es auch trennen :)

**Comment by phxql** [comment]
Ich würd's trennen.

**Comment by vlow** [comment]
Ich sehe keinen Vorteil darin, das zu zentralisieren. Da bekommt man nur technische Komplexität und Wartungsaufwand rein. Gleichzeitig kann das Frontend dann nichts rendern, ohne zusätzliche Requests ans Backend abzusetzen, obwohl es vll. nur um statische Texte wie beim Impressum geht.

**Comment by defaude** [comment]
Text **ist** UI. Text, der in der Angular App steht, sollte auch dort Teil der Codebase sein. Frontend-Texte **nur** dann ins Backend ziehen, wenn es ein bestimmtes Feature (CMS und so) zwingend nötig macht. Vorher auf gar keinen Fall.

Dass das Backend in seiner Codebase ebenfalls manche Texte hat... Nun ja, genau genommen sind die Mails (die vom Backend verschickt werden) ebenfalls eine eigenständige UI. Und da liegen die Texte eben auch in der korrekten Codebase ;)

**Comment by defaude** [comment]
Wurde mit #237 erledigt.
