### ISSUE TITLE
Konversionspunkte für Geschäfte und Kunden auf der Website

### ISSUE THREAD

**Issue by adersberger** [lokaler-kaufen/lokaler-kaufen-app#206]
IST: Geht man auf die lokaler.kaufen Website gibt es aktuell die den Aktionsbutton: "jetzt kostenlos starten" unterhalb der Erläuterung.

VORSCHLAG: Noch vor der Erläuterung zwei Buttons für jeweils den Einstieg als Geschäft (registrieren bzw. Administration) bzw. als Kunde (Geschäft suchen).

**Comment by vlow** [comment]
Die Website verschwindet demnächst in den Hintergrund, die Trennung ist bereits auf der Frontseite der App implementiert: https://github.com/qaware/wir-vs-virus/issues/214

Auf der Website können wir das zusätzlich anzeigen, die ist aber bald nicht mehr die Landing Page und so wie der Einstieg für Händler derzeit gebaut ist, ist das auch zusätzlicher Aufwand. Ist das Thema in diesem Kontext noch relevant?

**Comment by vlow** [comment]
Die Web-App ist jetzt die Startseite. Dort gibt es einen expliziten Absprungspunkt für Ladenbesitzer. Ich setze das Ticket daher auf erledigt.
