### ISSUE TITLE
Social Media Icons

### ISSUE THREAD

**Issue by vlow** [lokaler-kaufen/lokaler-kaufen-app#226]
Gerade bei den Läden mit Instagram und Facebook Präsenz sollte lokaler.kaufen ein guter Match für das Konzept sein. Wir sollten daher explizit im Profil Social Media Links erfassen und diese in Form hübscher Icons auf der Shop Detail Seite verlinken. Dabei können wir de Website auch gleich zu einer Weltkugel und die E-Mail-Adresse zu einem Briefchen machen.

Idee, wir listen das dann mit dem Bezeichner als Link auf:

🌐 Website | 🌐 Facebook | 🌐 Instagram

Jeweils mit den passenden Symbolen.

Zu klären: Vll. sollten wir das gleich oben bei der Beschreibung machen.

**Comment by vlow** [comment]
Evtl. könnte man auch nur die Symbole anzeigen.

**Comment by phxql** [comment]
Ich bereite im Backend mal was vor.

**Comment by phxql** [comment]
Die meisten Shop DTOs haben nun sowas:

```json
              "social": {
                "instagram": "insta.gram",
                "facebook": "face.book",
                "twitter": "@twitter"
              }
```

Das wird in der Datenbank gespeichert und an das Frontend gegeben.

**Comment by dashuber** [comment]
Ist im Frontend implementiert, probiert's gerne mal aus

**Comment by phxql** [comment]
Perfekt, danke!
