### ISSUE TITLE
Mindestvorlaufzeit

### ISSUE THREAD

**Issue by vlow** [lokaler-kaufen/lokaler-kaufen-app#227]
Manche Ladenbesitzer haben angemerkt, dass sie gerne eine Mindestvorlaufzeit vor dem nächsten Termin hätten. Mögliche Gründe dafür sind z.B. dass der Ladenbesitzer aktuell nicht dauernd im Laden ist, oder die Mail Notifications nicht regelmäßig genug sichtet.

Es sollte daher möglich sein, eine Mindestvorlaufzeit in Tagen, Stunden und Minuten anzugeben. Das könnte zumindest vorläufig auch gleich als Urlaubsfunktion genutzt werden.

**Comment by phxql** [comment]
in der `slotConfig` der Shops gibt's nun ein Feld namens `delayForFirstSlot`, das die Verzögerung für den ersten Slot in *Minuten* angibt. Das wird auch schon in der Datenbank gespeichert, aber noch nicht bei der Slot-Generierung ausgewertet. Aber das Frontend kann man schon mal dagegen bauen.

**Comment by phxql** [comment]
Wird nun auch in der Slot-Generierung berücksichtigt. Was noch fehlt ist ein Unit-Test, der das testet.

**Comment by dashuber** [comment]
Kann man jetzt im Frontend auch ausprobieren, schaut gut aus, dass es funktioniert @phxql 👍

**Comment by phxql** [comment]
Supergut!

**Comment by phxql** [comment]
Unit-Test geschrieben, damit ist das hier fertig!

**Comment by vlow** [comment]
Ich bin begeistert.
