### ISSUE TITLE
Fehlende Platzhalter-Substitution in Reservierungsmails

### ISSUE THREAD

**Issue by adersberger** [lokaler-kaufen/lokaler-kaufen-app#232]
Siehe folgendes Beispiel. Evtl. schafft man bei der Gelegenheit auch einen kürzeren Link.

Hallo Josef Adersberger,

phone360 - Smartphone & Tablet Reparatur  ruft Sie per FaceTime am 14.04.2020 zwischen {{ start }} Uhr und {{ end }} Uhr unter 01703075572 an.
Bitte beachten Sie, dass es zu Stoßzeiten zu Verzögerungen kommen kann.

Wenn Sie die Reservierung absagen möchten, klicken Sie bitte auf diesen Link:

https://app.lokaler.kaufen/#/cancel-reservation?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI3MTAzN2IwMi00YjM2LTRiZmEtYjlmYi1kNDhhNzRmNGJhMTgiLCJzaWRlIjoiY3VzdG9tZXIiLCJuYmYiOjE1ODY0NzIyMTcsImlzcyI6Im1lcmN1cnktcmVzZXJ2YXRpb24tY2FuY2VsbGF0aW9uIiwiZXhwIjoxNTg2ODQ4ODAwLCJpYXQiOjE1ODY0NzIyMTd9.g831SFm-_AptLBbWvE5spMYek6gQKBLq736ORy8yV8Q

Viele Grüße,

Ihr lokaler.kaufen Team

**Comment by vlow** [comment]
Done

**Comment by vlow** [comment]
Fix in Produktion ausgerollt
