### ISSUE TITLE
Lazy-Loading für Bilder aktivieren

### ISSUE THREAD

**Issue by defaude** [lokaler-kaufen/lokaler-kaufen-app#234]
Um Bandbreite zu sparen, ist es ratsam, Bilder nur dann zu laden, wenn sie wirklich im Viewport des Nutzers auftauchen.

Empfehlung: Die von den Nutzern hochgeladenen Bilder mit `loading="lazy"` versehen. Das ist ein cooles Feature, das **endlich** dieses Problem entspannt löst. Browser, die das noch nicht unterstützen, laden die Bilder einfach weiterhin wie gehabt.

[Dokumentation](https://developer.mozilla.org/de/docs/Web/Performance/Lazy_loading#Images)

[Browser Support](https://caniuse.com/#feat=loading-lazy-attr)

**Comment by dashuber** [comment]
LGTM
