### ISSUE TITLE
Fehlender Redirect bei ungültigem Admin-Token

### ISSUE THREAD

**Issue by vlow** [lokaler-kaufen/lokaler-kaufen-app#236]
Wenn mein Admin-Token ausgelaufen ist und ich versuche direkt auf die Admin-Seite zu gehen, erwarte ich, dass ich auf die Admin-Login-Seite umgelenkt werde und nach dem Login auf die ursprünglich von mir angesurfte Seite weitergeleitet werde, in diesem Fall https://app.lokaler.kaufen/#/admin/overview

Stattdessen bekomme ich aber eine Fehlermeldung, dass beim Laden der Daten ein Fehler aufgetreten ist. Das sollte für die Detailseiten genauso gelten: Login und dann auf die ursprünglich angesurfte Seite weiterleiten.

**Comment by defaude** [comment]
Auch hierfür müssten wir 
- alle möglichen Service Calls in eine eigene Schicht schieben
- App-weites State Management einführen (redux oder von mir aus ngrx)

**Comment by vlow** [comment]
In diesem Fall wäre es schon eine Verbesserung, wenn bei nem 401 einfach _immer_ die Login Seite aufgerufen wird. Der Login führt dann halt immer zur Overview, aber ich muss zumindest nicht mehr manuell die /admin URL aufrufen, um mich einzuloggen.

**Comment by defaude** [comment]
Man **könnte** einen Interceptor bauen, der alle 401er frisst und dann (vielleicht) abhängig von Admin oder nicht auf die eine oder die andere Login-Seite redirected.
