### ISSUE TITLE
GraphicsMagic entfernt Alpha-Kanal bei PNGs

### ISSUE THREAD

**Issue by vlow** [lokaler-kaufen/lokaler-kaufen-app#241]
Wenn man ein PNG mit gültiger Alpha-Transparenz hochlädt, fehlt dem Bild bei der Anzeige der Alpha-Kanal und wird durch schwarz ersetzt.

**Comment by phxql** [comment]
Wir konvertieren ins JPG-Format, das kann keine Alpha-Transparenz. Wir haben hier zwei Möglichkeiten:

1. Wir transformieren statt zu JPG zu PNG (etwas mehr Aufwand, das umzubauen)
2. Wir setzen statt schwarz ne andere Farbe, z.b. weiß und bleiben bei JPG

**Comment by phxql** [comment]
Als quick fix setz ich mal weiß als alpha-ersatz, dann schauen wir wie das aussieht.
