### ISSUE TITLE
Fehler beim Logo upload

### ISSUE THREAD

**Issue by rohleder** [lokaler-kaufen/lokaler-kaufen-app#246]
Wenn ich das Logo hochlade und dann speichere, bekomme ich eine Fehlermeldung.
Tritt auch in Produktion auf und wurde von einem Händler gemeldet.
![foglwuid_logo_gruen_300dpi](https://user-images.githubusercontent.com/11029373/79330357-a9543700-7f19-11ea-8696-e2a2fd31a0fa.jpg)
![Screenshot_20200415-130138](https://user-images.githubusercontent.com/11029373/79330359-aa856400-7f19-11ea-8a2b-77dcb687c28e.png)

**Comment by rohleder** [comment]
Tritt auch in der Testumgebung auf

**Comment by phxql** [comment]
Der Nginx lehnt den Request mit `413 Request Entity too large` ab. Ich fix die nginx config.

**Comment by phxql** [comment]
Ist gefixt!

Technische Info:

```
       	    # Allow large image	uploads
            client_max_body_size 6M;  
```

in die `location` beim backend proxy rein.
