### ISSUE TITLE
"Bild löschen" bei Shop bearbeiten funktioniert nicht

### ISSUE THREAD

**Issue by phxql** [lokaler-kaufen/lokaler-kaufen-app#247]
1. Einloggen als Shop
1. In die Section ganz nach unten wechseln
1. Auf "Bild löschen" drücken

Expected: Bild ist weg
Actual: Bild ist noch da

**Comment by dashuber** [comment]
Sieht nach Backend Bug aus, ich krieg im Frontend bei dem `/api/shop/shop-id` nach Löschen des Bildes (und 200er auf den `DELETE /api/image/shop`) immer noch die alte Image URL zurück.

**Comment by dashuber** [comment]
Problem war, dass das Frontend den `DELETE` und den `PUT` mit den Updates direkt nacheinander geschickt hat. Wir warten jetzt, bis der `DELETE` zurückkommt und schicken dann erst das Update raus.
