### ISSUE TITLE
Falscher Text in der Absagebestätigung-Notification

### ISSUE THREAD

**Issue by phxql** [lokaler-kaufen/lokaler-kaufen-app#250]
Wenn ich als Ladenbesitzer auf den Absagenlink klicke, bekomme ich eine grüne Notification mit dem Text "Wir haben den Ladenbesitzer informiert". Aber der bin ich. Da ist n falscher Text drin, oder es wird keine Unterscheidung zwischen Absage Kunde / Laden gemacht. Quick fix: Passend für beide Fälle formulieren

**Comment by dashuber** [comment]
Habs zu "Der Beratungstermin wurde storniert" geändert.
