### ISSUE TITLE
https://info.lokaler.kaufen hat kein gültiges HTTPS Zertifikat

### ISSUE THREAD

**Issue by defaude** [lokaler-kaufen/lokaler-kaufen-app#255]

**Comment by vlow** [comment]
Die nginx-Konfiguration dafür habe ich heute erst angelegt, deshalb war die Seite zwischendrin schon erreichbar, hatte aber noch kein Zertifikat. Inzwischen ist die Konfiguration fertig und das Zertifikat existiert.
