### ISSUE TITLE
Outline bei Links entfernen

### ISSUE THREAD

**Issue by vlow** [lokaler-kaufen/lokaler-kaufen-app#268]
Die Links haben momentan nach dem Klick eine sichtbare Outline. Das kann man leicht im Stylesheet durch das Anfügen der folgenden Definition unterbinden:

```
a:active, a:focus, a:visited { outline: none; }
```

**Comment by basalt79** [comment]
hi @vlow , ich werde es versuchen

**Comment by basalt79** [comment]
@vlow can you have a look on the PR and tag it with `hacktoberfest-accepted` thx

**Comment by vlow** [comment]
done, fixed by @basalt79
