### ISSUE TITLE
Idee: Termineintrag an Mail anhängen 

### ISSUE THREAD

**Issue by VPaulisch** [lokaler-kaufen/lokaler-kaufen-app#59]
Idee: Als Shop-Betreiber oder Kunde will ich den vereinbarten Termin direkt in meinen Kalender übernehmen können, damit ich diese Zeitslot frei halten und Erinnerungen dazu erhalten kann.

Wenn ein Termin ausgemacht wird könnte in der Bestätigungsmail (sowohl für Kunde als auch Shop) ein .ics-Kalendereintrag angehängt werden.

**Comment by FelixKelm** [comment]
+1
Von einem Bekannten, der sich registriert hat, kam auch der Vorschlag, einen Termineintrag mit Kontaktdaten zu verschicken.

**Comment by phxql** [comment]
Implementiert. ich habs mit Thunderbird & gmail getestet, wir sollten das noch mit apple testen.
