### ISSUE TITLE
UI/Backend: Jeder Shop soll mindestens ein Bild/Logo von sich hochladen

### ISSUE THREAD

**Issue by dashuber** [lokaler-kaufen/lokaler-kaufen-app#73]
Speichern, Löschen und Update im Backend nötig, Darstellung im Frontend betrifft Shop Übersichtsseite, Detail Page, Admin Page, Shop Creation. Evtl. Default Bild, falls jemand keins hochlädt

**Comment by dominikhaas** [comment]
Ich schlage vor, dass wir ein Defaultbild haben und keine Pflicht -> geringere Hürde

**Comment by dashuber** [comment]
Cool wäre ein "passendes" Bild zum Shop, wie das z. B. Google Kalendar auch macht, bei Kaffee mit... ein Kaffeebild, bei Mittagessen mit... ein Bild von Essen. Aber keine Ahnung, ob das so einfach geht 🤷‍♀

**Comment by dashuber** [comment]
@phxql @zalintyre Das Feature wird vermehrt von den Ladenbesitzern angefragt. Sollten das Thema höher priorisieren

**Comment by phxql** [comment]
Okay - ein Bild pro Shop reicht? Oder soll das so ne Galerie werden?

**Comment by dashuber** [comment]
Ich vermute auf Dauer wollen die Shops ne Galerie, also könnten wir so ein klassisches maximal 5 Bilder pro Shop Ding machen. Eins ist das Thumbnail Bild (vermutlich das Logo), das dann auch auf der Übersichtsseite angezeigt wird.

**Comment by vlow** [comment]
done
